pipeline {
    agent any
    environment {
        TF_VAR_gcp_project = "qwiklabs-gcp-XX-XXXXXXXXXXXX"
        TF_VAR_bucket = "terraform-state-XXXXXX-XXXX-XXXXX"
        REPO = "<your repo url>"
    }
    stages {
        stage('Checkout Repository') {
            steps {
                // Clone the repository to the Jenkins workspace
                git url: ${REPO}, branch: "main"
            }
        }
        stage('Terraform Init') {
            steps {
                withCredentials([file(credentialsId: 'gcp-svc-acct', variable: 'GOOGLE_CLOUD_KEYFILE_JSON')]) {
                    sh '''
                    export GOOGLE_APPLICATION_CREDENTIALS=$GOOGLE_CLOUD_KEYFILE_JSON
                    terraform init
                    terraform plan -destroy
                    '''
                }
            }
        }
        stage('Destroy') {
            steps {
                dir('./') { // Ensure the correct directory is used
                    // Manual approval prompt
                    input message: "Are you sure you want to destroy the resources?", ok: "Yes, Destroy"
                    withCredentials([file(credentialsId: 'gcp-svc-acct', variable: 'GOOGLE_CLOUD_KEYFILE_JSON')]) {
                        sh '''
                        export GOOGLE_APPLICATION_CREDENTIALS=$GOOGLE_CLOUD_KEYFILE_JSON
                        terraform destroy -auto-approve -lock=false
                        '''
                    }
                }
            }
        }
    }
}